import 'dart:io';
import 'package:path/path.dart' as path;

enum TemplateType { database, config }

class TemplateUtils {
  String readTemplate(TemplateType templateType) {
    String pathFile;
    print(Directory.current.absolute.path);
    switch (templateType) {
      case TemplateType.database:
        pathFile = path.joinAll([Directory.current.absolute.path,'templates','database.json']);
        break;
      case TemplateType.config:
        pathFile = path.joinAll([Directory.current.absolute.path,'templates','config.yaml']);
        break;
    }
    

    final templateFile = File(pathFile);
    return templateFile.readAsStringSync();
  }

  String _pathFile(String fileName) {
    var context;
    // get platform context
    if (Platform.isWindows) {
      context = path.Context(style: path.Style.windows);
    } else {
      context = path.Context(style: path.Style.posix);
    }

    // case baseDir not informed, get current script dir
    var baseDir = path.dirname(Platform.script.path);
    var filePath = context.join(baseDir, fileName);
    // convert Uri to String to make the string treatment more easy
    filePath = context.fromUri(context.normalize(filePath));
    // remove possibles extra paths generated by testing routines
    filePath = path.fromUri(filePath).split('file:').last;

    return filePath;
  }
}
